// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARypRnxeMkPRE3s04P0xrDv00mneaxJhY',
    appId: '1:89918709345:web:4d489cf5b06c763cc75420',
    messagingSenderId: '89918709345',
    projectId: 'project-valdo',
    authDomain: 'project-valdo.firebaseapp.com',
    storageBucket: 'project-valdo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL_2R3GVSn4-lCv6-ppEWcWxZUZU63Q0k',
    appId: '1:89918709345:android:b6c5e01f5257c721c75420',
    messagingSenderId: '89918709345',
    projectId: 'project-valdo',
    storageBucket: 'project-valdo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCswxxiRy9-ugcq8jZHCLplBQeOJkd1Zvw',
    appId: '1:89918709345:ios:68874ad29f894f18c75420',
    messagingSenderId: '89918709345',
    projectId: 'project-valdo',
    storageBucket: 'project-valdo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCswxxiRy9-ugcq8jZHCLplBQeOJkd1Zvw',
    appId: '1:89918709345:ios:68874ad29f894f18c75420',
    messagingSenderId: '89918709345',
    projectId: 'project-valdo',
    storageBucket: 'project-valdo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARypRnxeMkPRE3s04P0xrDv00mneaxJhY',
    appId: '1:89918709345:web:5a6bff7ecf07192dc75420',
    messagingSenderId: '89918709345',
    projectId: 'project-valdo',
    authDomain: 'project-valdo.firebaseapp.com',
    storageBucket: 'project-valdo.appspot.com',
  );

}